LINUXDROID_PKG_HOMEPAGE=https://www.aircrack-ng.org
LINUXDROID_PKG_DESCRIPTION="an 802.11 WEP and WPA-PSK keys cracking program"
LINUXDROID_PKG_VERSION=1.2-rc4
LINUXDROID_PKG_REVISION=3
LINUXDROID_PKG_SRCURL=https://download.aircrack-ng.org/aircrack-ng-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_SHA256=d93ac16aade5b4d37ab8cdf6ce4b855835096ccf83deb65ffdeff6d666eaff36
LINUXDROID_PKG_MAINTAINER="Auxilus @Auxilus"
LINUXDROID_PKG_DEPENDS="libnl, openssl, libpcap, pciutils"
LINUXDROID_PKG_BUILD_DEPENDS="libnl-dev, openssl-dev, libpcap-dev"
LINUXDROID_PKG_BUILD_IN_SRC=yes
