LINUXDROID_PKG_HOMEPAGE=hhttps://www.kernel.org/pub/software/network/ethtool/
LINUXDROID_PKG_DESCRIPTION="standard Linux utility for controlling network drivers and hardware, particularly for wired Ethernet devices"
LINUXDROID_PKG_VERSION=4.11
LINUXDROID_PKG_REVISION=1
LINUXDROID_PKG_SRCURL=https://www.kernel.org/pub/software/network/ethtool/ethtool-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_SHA256=af2fd9692f3159d3ab1e41e6f9b7d8db2a4693f1cb22348c88ba89f70f0e6503
LINUXDROID_PKG_MAINTAINER="Auxilus @Auxilus"
LINUXDROID_PKG_DEPENDS="libnl" 
LINUXDROID_PKG_BUILD_IN_SRC=yes
