LINUXDROID_PKG_MAINTINER="Henrik Grimler @Grimler91"
LINUXDROID_PKG_HOMEPAGE=https://github.com/vgough/encfs
LINUXDROID_PKG_DESCRIPTION="EncFS provides an encrypted filesystem in user-space"
LINUXDROID_PKG_VERSION=1.9.5
LINUXDROID_PKG_SHA256=4709f05395ccbad6c0a5b40a4619d60aafe3473b1a79bafb3aa700b1f756fd63
LINUXDROID_PKG_DEPENDS="libfuse, openssl"
LINUXDROID_PKG_SRCURL=https://github.com/vgough/encfs/archive/v${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="
-DFUSE_INCLUDE_DIR=$LINUXDROID_PREFIX/include
-DFUSE_LIBRARIES=$LINUXDROID_PREFIX/lib/libfuse.so
-DRUN_HAVE_POSIX_REGEX=0
-DRUN_HAVE_STD_REGEX=0
-DRUN_HAVE_STEADY_CLOCK=0
"

linuxdroid_step_pre_configure () {
	LDFLAGS="$LDFLAGS -llog"
}
