LINUXDROID_PKG_HOMEPAGE=https://github.com/traviscross/mtr
LINUXDROID_PKG_DESCRIPTION="Network diagnostic tool"
LINUXDROID_PKG_VERSION=0.92
LINUXDROID_PKG_REVISION=1
LINUXDROID_PKG_SHA256=568a52911a8933496e60c88ac6fea12379469d7943feb9223f4337903e4bc164
LINUXDROID_PKG_SRCURL=https://github.com/traviscross/mtr/archive/v${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_DEPENDS="ncurses"
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="--without-gtk"

linuxdroid_step_pre_configure() {
	cp $LINUXDROID_PKG_BUILDER_DIR/hsearch/* $LINUXDROID_PKG_SRCDIR/portability

	cd $LINUXDROID_PKG_SRCDIR
	./bootstrap.sh
}
